### ISSUE TITLE
Endpoint details set in RequestSpecification aren't properly applied to endpoint

### ISSUE THREAD

**Issue by bheemreddy181** [basdijkstra/rest-assured-net#22]
Currently, we support C# class objects for reading the Input API request , we might not need C# class objects all the time rather than creating a raw JSON for such cases can we support dictionary objects ?

**Comment by basdijkstra** [comment]
Json.NET has got you covered on that already. I've added an example to make this more clear, and I will add that to the docs as well: https://github.com/basdijkstra/rest-assured-net/blob/fcde102dfad1731aa703fd5b346ff61312b3353d/RestAssured.Net.Tests/RequestBodySerializationTests.cs#L90

Does that answer your question? If so please close this issue, if not, please elaborate.

**Comment by bheemreddy181** [comment]
Interesting, I was getting the below error with a dictionary 

```
System.AggregateException : One or more errors occurred. (The 'file' scheme is not supported.)
  ----> System.NotSupportedException : The 'file' scheme is not supported.
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at RestAssuredNet.RA.ExecutableRequest.Send(HttpMethod httpMethod, String endpoint)
   at RestAssuredNet.RA.ExecutableRequest.Post(String endpoint)
   at IntegrationTests.Tests.CreateLeadTests.CreateLeadTest() in /Users/bheemvennapureddy/SummitApi/IntegrationTests/Tests/CreateLeadTests.cs:line 33
--NotSupportedException
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at RestAssuredNet.RA.Internal.HttpRequestProcessor.Send(HttpRequestMessage request, CookieCollection cookieCollection)
```

**Comment by basdijkstra** [comment]
Can you add the test that you used?

**Comment by bheemreddy181** [comment]
Let me debug this a bit more and provide a detailed info on this.

**Comment by basdijkstra** [comment]
Thanks.

Do you have a GitHub link somewhere where I can find the test? If not I’ll rebuild it myself but I might end up not having the exact same situation.

Can you see in your debug session what the complete endpoint is that RestAssured is trying to invoke?

**Comment by basdijkstra** [comment]
Hmm..

When I use the same setup like this with v1.0.0:

```csharp
private RequestSpecification requestSpec;

        [SetUp]
        public void CreateRequestSpecification()
        {
            requestSpec = new RequestSpecBuilder()
                .WithScheme("http")
                .WithHostName("api.zippopotam.us")
                .WithBasePath("us")
                .Build();
        }

        [Test]
        public void CheckResponseStatusCodeAndJsonResponseBodyElementValue()
        {
            Given()
                .Spec(requestSpec)
                .When()
                .Get("/90210")
                .Then()
                .Body("$.places[0].state", NHamcrest.Is.EqualTo("California"));
        }
```

It works as expected. Again, can you please tell me what the endpoint is that RestAssured is trying to hit?

**Comment by bheemreddy181** [comment]
looks like i am using the formatUrlEnocoded branch not that master ( 1.0.0 ) - Can you try on that branch ?

**Comment by basdijkstra** [comment]
No, because that doesn't exist anymore. Can we leave this open until the next release? That should not take me more than a couple of days now, and since I've done quite a bit of work on the `RequestSpecification`, things might have changed for the better for you :)

**Comment by bheemreddy181** [comment]
Sure that works

**Comment by bheemreddy181** [comment]
![Uploading Screen Shot 2022-11-10 at 1.09.50 PM.png…]()

**Comment by bheemreddy181** [comment]
<img width="1108" alt="Screen Shot 2022-11-10 at 1 09 50 PM" src="https://user-images.githubusercontent.com/101338506/201185207-6360faf1-9925-43e1-8ec2-607454af8224.png">

**Comment by basdijkstra** [comment]
Yes, but the _actual_ endpoint is only constructed _inside_ the `Send()` method, that's where the `RequestSpecification` is applied.

See here: https://github.com/basdijkstra/rest-assured-net/blob/9d96a25d723e01f56dc9125f250849b9093f4ed9/RestAssured.Net/RA/ExecutableRequest.cs#L418

 Can you debug into that? Or use Fiddler or WireShark to see what the outgoing traffic is, that's the actual endpoint.

**Comment by bheemreddy181** [comment]
this is what i see 
<img width="854" alt="Screen Shot 2022-11-10 at 1 18 38 PM" src="https://user-images.githubusercontent.com/101338506/201186783-0ed4299b-0499-41ff-b458-3e65563115bd.png">

**Comment by basdijkstra** [comment]
Thanks, that's what I was looking for. That's definitely not good.

Once again, let's park this until the next proper release. If it's still there, I'll try and fix that ASAP but I probably need you to publish this on GitHub (or send it to me via email: bas@ontestautomation.com) so I can reproduce it.

**Comment by bheemreddy181** [comment]
Sure i can create an example on Github

**Comment by bheemreddy181** [comment]
https://github.com/bheemreddy181/restAssuredNetTest example repo

**Comment by basdijkstra** [comment]
Thanks. The error I'm getting when running your test with version 1.0.0 is slightly different:

`System.AggregateException : One or more errors occurred. (The SSL connection could not be established, see inner exception.)
  ----> RestAssuredNet.RA.Exceptions.HttpRequestProcessorException : The SSL connection could not be established, see inner exception.`

I've seen that with other HTTPS calls, too, and I'll address it in #13. Thank you for uploading that example!

Again, let's keep this open until version 1.1.0 is released and test again.

**Comment by bheemreddy181** [comment]
Sounds good thanks

**Comment by basdijkstra** [comment]
OK, I've found the problem (and another one in the logging, too). The problem is that the RequestSpecification port defaults to 80, which is not a useful value when you use https (it should be 443 in that case). When you change the port to 443, it works (or well, you get an HTTP 401 Unauthorized because your token value is invalid) as well as a NullReferenceException because there is no body to log and you call `Log().All()`.

![image](https://user-images.githubusercontent.com/10740451/201415340-8bceb1ed-99b3-46c1-88a7-d3865d538cab.png)

I'll create separate issues for those, is it OK to close this one then, @bheemreddy181?

**Comment by bheemreddy181** [comment]
Gotcha - Sounds good to me wasn't that defaulting to port 80 before too ?

**Comment by basdijkstra** [comment]
> Gotcha - Sounds good to me wasn't that defaulting to port 80 before too ?

Yes and it still does, because that's the default port for HTTP, but not for HTTPS. I might be better off not setting a default at all..

**Comment by basdijkstra** [comment]
Anyway, closing this one, we can always continue the conversation in the other issue.

**Comment by bheemreddy181** [comment]
> > Gotcha - Sounds good to me wasn't that defaulting to port 80 before too ?
> 
> Yes and it still does, because that's the default port for HTTP, but not for HTTPS. I might be better off not setting a default at all..

Agree there let people decide their own port

**Comment by basdijkstra** [comment]
Hye @bheemreddy181, just wanted to let you know that this issue has been resolved with https://github.com/basdijkstra/rest-assured-net/commit/ceba3f5fcbf564be3e8b7d57a38d5ddea9405a29. Turns out there is a port value (-1) that looks at the scheme, so that is used as the default now. It can of course still be overridden in a test and request specification.

Tested this using the upcoming 1.1.1 release (give me a couple of minutes) with your code and it now throws the expected HTTP 401 (because your token is invalid).

**Comment by bheemreddy181** [comment]
I still see the port as -1 even on the new version, do we need to set the port to 443 on the request specification ? (which we shouldn't be) what am i missing here ? 
<img width="515" alt="Screen Shot 2022-11-13 at 12 34 05 PM" src="https://user-images.githubusercontent.com/101338506/201538428-f429c644-1568-4c81-8d40-764f8de6d080.png">
 
<img width="1041" alt="Screen Shot 2022-11-13 at 12 33 07 PM" src="https://user-images.githubusercontent.com/101338506/201538441-93eb9bdd-3ba8-44db-b2cd-1c5ab0297336.png">

**Comment by basdijkstra** [comment]
The port will be set to the scheme default in the HttpClient, so it’s OK for it to be -1 in the RequestSpecification. When the HTTP call is made and the port is -1, HttpClient will replace it with the scheme default (80 for HTTP, 443 for HTTPS).

**Comment by bheemreddy181** [comment]
Gotcha well I am still getting the old error though I need to debug more , the request URI is still not being set correctly

**Comment by bheemreddy181** [comment]
If you look at the request uri above in the second screenshot that is still set to ‘file:///lead’

**Comment by bheemreddy181** [comment]
is that ok to keep this request open until things get cleared on my side ?

**Comment by bheemreddy181** [comment]
Looks like you are framing the actual endpoint when the URI builder throws an exception, in my case I don't see an exception is being thrown here 
<img width="1189" alt="Screen Shot 2022-11-13 at 3 20 52 PM" src="https://user-images.githubusercontent.com/101338506/201545206-a78bb64e-ad5c-468d-98f3-2808d53a40ed.png">

**Comment by basdijkstra** [comment]
Yeah, happy to keep this open. It's really weird, though, because the `UriFormatException` should be thrown here according to the Microsoft docs (which are typically very accurate):

![image](https://user-images.githubusercontent.com/10740451/201596321-8279a52a-e672-42fa-9910-aaad8ed0eb2c.png)

The last sentence is key here. What you're passing in is a relative Uri, and that should throw the `UriFormatException` leading to the actual Uri being built from the RequestSpecification.

**Comment by bheemreddy181** [comment]
I think this is the issue https://github.com/dotnet/runtime/issues/27813

**Comment by bheemreddy181** [comment]
I think you might need to do something of this sort 
`Uri uri = new Uri(url);
    try
    {
        string host = uri.Host;
    }
    catch (UriFormatException)
    {
        Console.WriteLine("Bad url: {0}", url);
    } `

**Comment by basdijkstra** [comment]
That explains a lot of things... So, what .NET version are you using (the issue talks about .NET Core 2.1) and what operating system are you on? Just for my information :) I will need to find a way to fix / work around this.

**Comment by bheemreddy181** [comment]
I am on dotnet 6 and Operating system Mac OS.

**Comment by basdijkstra** [comment]
Thanks! It was only time before I'd run into cross-OS compatibility issues, I guess.. I'll have a look and see how to best fix this. I'll take your solution into account.

**Comment by bheemreddy181** [comment]
Sounds good thanks.

**Comment by basdijkstra** [comment]
Hey @bheemreddy181, I think I've fixed this now. Could you please retest with RestAssured.Net version `1.2.0-alpha`, which is available as a prerelease through NuGet?

**Comment by bheemreddy181** [comment]
Sure will test sometime today.

**Comment by bheemreddy181** [comment]
Yes that worked. .RelaxedHttpsValidation() is what I am a bit confused on, why do I need to add that all the time for all requests. (Probably a different issue we can talk on)

**Comment by bheemreddy181** [comment]
I understand that token generation worked with RelaxedHttpsValidation before and all of a sudden this is a required in the implementation did something change around that ?

**Comment by bheemreddy181** [comment]
Thanks for the explanation.Ya will do.
